### ISSUE TITLE
Unresolved import 'rp2040_hal::pac::interrupt'

### ISSUE THREAD

**Issue by Hellstormer00** [rp-rs/rp-hal#320] opened 2022-03-25 18:53 UTC
When i try to 

`use rp2040_hal::pac::interrupt;`

I get the error that the interrupt module/macro is not found.
My cargo.toml looks like this

```rust
...

[dependencies]
rp2040-hal = "0.4"
cortex-m-rt = "0.7"
panic-halt = "0.2"
usbd-hid = "0.5.1"
usb-device = "0.2.8"

...
```

I can't use the `#[interrupt]` macro

**Comment by 9names** [comment] 2022-03-25 22:28
You need to enable the `rt` feature to get this import from the PAC.
```
rp2040-hal = { version = "0.4", features = ["rt"]}
```

The [project template](https://github.com/rp-rs/rp2040-project-template/blob/f4fd405c917ee4d077f70bff63c46b76f6db1838/Cargo.toml#L26) is a good reference for this sort of info.

**Comment by 9names** [comment] 2022-05-15 05:18
@Hellstormer00: Has this resolved your issue?

**Comment by jannic** [comment] 2022-06-22 18:27
I verified that a missing `rt` feature gives an error message matching the report:
```
error[E0432]: unresolved import `hal::pac::interrupt`
  --> boards/rp-pico/examples/pico_pwm_audio.rs:16:5
   |
16 |     pac::interrupt,
   |     ^^^^^---------
   |     |    |
   |     |    help: a similar name exists in the module (notice the capitalization): `Interrupt`
   |     no `interrupt` in the root
```
Therefore I assume that the hint in https://github.com/rp-rs/rp-hal/issues/320#issuecomment-1079488648 was correct. Closing the ticket now, @Hellstormer00, feel free to reopen it in case I was wrong and your issue was caused by something else.

**Closed as completed by jannic** 2022-06-22 18:27 UTC
